### ISSUE TITLE
Crash adding NPC faction task.

### ISSUE THREAD

**Issue by GreatOrator** [Funwayguy/NPC_Integration#10]
Added a quest task for an NPC faction, as soon as I closed out of the edit to see the quest, this:

java.lang.NullPointerException: Rendering screen
	at noppes.npcs.controllers.PlayerDataController.getDataFromUsername(PlayerDataController.java:47)
	at bq_npc_integration.client.gui.tasks.GuiTaskNpcFaction.drawBackground(GuiTaskNpcFaction.java:37)
	at betterquesting.api.client.gui.GuiScreenThemed.drawBackPanel(GuiScreenThemed.java:96)
	at betterquesting.client.gui.GuiQuestInstance.drawBackPanel(GuiQuestInstance.java:129)
	at betterquesting.api.client.gui.GuiScreenThemed.func_73863_a(GuiScreenThemed.java:108)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at noppes.npcs.controllers.PlayerDataController.getDataFromUsername(PlayerDataController.java:47)
	at bq_npc_integration.client.gui.tasks.GuiTaskNpcFaction.drawBackground(GuiTaskNpcFaction.java:37)
	at betterquesting.api.client.gui.GuiScreenThemed.drawBackPanel(GuiScreenThemed.java:96)
	at betterquesting.client.gui.GuiQuestInstance.drawBackPanel(GuiQuestInstance.java:129)
	at betterquesting.api.client.gui.GuiScreenThemed.func_73863_a(GuiScreenThemed.java:108)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: betterquesting.client.gui.GuiQuestInstance
	Mouse location: Scaled: (360, 405). Absolute: (721, 37)
	Screen size: Scaled: (720, 424). Absolute: (1440, 847). Scale factor of 2

this is using your alpha version you provided for me to test 2.3.20, also does not save but does crash each time I try to create a faction quest.

**Comment by BakermanLP** [comment]
Cross Ref https://github.com/BakermanLP/ProjectRET-AoT/issues/76
Could that be a similar problem?
http://pastebin.com/sEf1mNxP

**Comment by GreatOrator** [comment]
Yup, looks almost exactly like my crash.  I know he is working on some issues with this, and apparently CNPC made changes that broke the integration so he is trying to find a work-around.

**Comment by Funwayguy** [comment]
To be more accurate, I'm almost certain it's because CNPC doesn't sync data client side unless it explicitly requests it on demand (i.e. opening a GUI that uses it) so BQ would have to manually sync everything itself, not ideal.
